-- Command centers: a central admin chat that manages a set of connected chats.
-- These tables are new; do not edit this file after it has been applied.

CREATE TABLE IF NOT EXISTS command_centers (
    id BIGSERIAL PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    owner_id BIGINT NOT NULL,
    name VARCHAR(64) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_command_centers_chat_id ON command_centers (chat_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_command_centers_owner_id ON command_centers (owner_id);

CREATE TABLE IF NOT EXISTS command_center_chats (
    id BIGSERIAL PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    command_id BIGINT NOT NULL,
    is_quiet BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_command_center_chats_chat_id ON command_center_chats (chat_id);
CREATE INDEX IF NOT EXISTS idx_command_center_chats_command_id ON command_center_chats (command_id);

CREATE TABLE IF NOT EXISTS command_center_action_logs (
    id BIGSERIAL PRIMARY KEY,
    command_id BIGINT NOT NULL,
    chat_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    action_type TEXT NOT NULL,
    reason TEXT NOT NULL DEFAULT '',
    message_id BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_command_center_action_logs_command_id ON command_center_action_logs (command_id);
